package com.conaxgames.api.redis;

import com.conaxgames.libraries.redis.message.MessageTypeInterface;

public enum MessageType implements MessageTypeInterface {
    UNKNOWN,

    HEARTBEAT,
    BROADCAST,
    SEND_MESSAGE,
    SEND_CLICKABLE,
    BROADCAST_CLICKABLE,
    SOCIAL_SPY,
    KICK_PLAYER,
    KICK_PLAYER_NAME,
    KICK_IP,
    EXECUTE_COMMAND,
    RELOAD_NETWORK_CONFIG,

    SCOPE_CREATE,
    SCOPE_DELETE,
    SCOPE_EDIT,

    RANK_CREATE,
    RANK_DELETE,
    RANK_PERMISSION_ADD,
    RANK_PERMISSION_REMOVE,
    RANK_PERMISSION_CLEAR,
    RANK_SCOPED_PERMISSION_ADD,
    RANK_SCOPED_PERMISSION_REMOVE,
    RANK_SCOPED_PERMISSION_CLEAR,
    RANK_INHERITANCE_ADD,
    RANK_INHERITANCE_REMOVE,
    RANK_EDIT_NAME,
    RANK_EDIT_PREFIX,
    RANK_EDIT_COLOR,
    RANK_EDIT_WEIGHT,

    VELOCITY_PLAYER_PERMISSIONS,
    VELOCITY_SEND_MESSAGE,
    VELOCITY_STAFF_SERVER_SWITCH,
    VELOCITY_FRIEND_SERVER_SWITCH,

    TAG_CREATE,
    TAG_DELETE,
    TAG_EDIT,
    TAG_EDIT_NAME,
    TAG_EDIT_STYLE,
    TAG_EDIT_DESCRIPTION,
    TAG_EDIT_STORE_STATUS,
    TAG_EDIT_SUFFIX,
    TAG_EDIT_PRIVATE,

    GUILD_CHAT,
    GUILD_UPDATE,

    STAFF_STATUS_UPDATE,

    MAINTENANCE_STATE,
    MAINTENANCE_WHITELIST
}
